INSERT INTO user VALUES (1, 'user', 'user@mail.ru', '{noop}user');
INSERT INTO user VALUES (2, 'user2', 'user2@mail.ru', '{noop}user2');

INSERT INTO task VALUES (1, 'day_1_task_1', CURRENT_TIMESTAMP() - 1, CURRENT_TIMESTAMP(), FALSE, 1);
INSERT INTO task VALUES (2, 'day_1_task_2', CURRENT_TIMESTAMP() - 1, CURRENT_TIMESTAMP(), FALSE, 1);
INSERT INTO task VALUES (3, 'day_1_task_3', CURRENT_TIMESTAMP() - 1, CURRENT_TIMESTAMP(), FALSE, 1);

INSERT INTO task VALUES (4, 'day_2_task_1', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP() + 1, FALSE, 1);
INSERT INTO task VALUES (5, 'day_2_task_2', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP() + 1, FALSE, 1);
INSERT INTO task VALUES (6, 'day_2_task_3', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP() + 1, FALSE, 1);

INSERT INTO task VALUES (7, 'day_3_task_1', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP() + 2, FALSE, 1);
INSERT INTO task VALUES (8, 'day_3_task_2', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP() + 2, FALSE, 1);
INSERT INTO task VALUES (9, 'day_3_task_3', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP() + 2, FALSE, 1);

INSERT INTO task VALUES (10, 'day_4_task_1', CURRENT_TIMESTAMP() - 1, CURRENT_TIMESTAMP(), FALSE, 2);
INSERT INTO task VALUES (11, 'day_4_task_2', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP() + 1, FALSE, 2);
INSERT INTO task VALUES (12, 'day_4_task_3', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP() + 2, FALSE, 2);